In [3]:
!pip install --disable-pip-version-check -q awscli boto3
!pip install --disable-pip-version-check -q PyAthena
!pip install --disable-pip-version-check -q sagemaker
!pip install --disable-pip-version-check -q pandas

ERROR: To modify pip, please run the following command:
C:\Program Files\Python313\python.exe -m pip install --disable-pip-version-check -q pip --upgrade
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [21 lines of output]
  + C:\Program Files\Python313\python.exe C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9\vendored-meson\meson\meson.py setup C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9 C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9\.mesonpy-w5gyi215 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9\.mesonpy-w5gyi215\meson-python-native-file.ini
  The Meson build system
  Version: 1.2.99
  Source dir: C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9
  Build dir: C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9\.mesonpy-w5gyi215
  Build type: native build
  Project name: NumPy
  Project version: 1.26.4
  WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

  ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
  The following exception(s) were encountered:
  Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
  Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
  Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
  Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
  Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
  Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
  Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

  A full log can be found at C:\Users\dcode\AppData\Local\Temp\pip-install-l6s7d6k4\numpy_ba49616d909b43a9b9238d8ba4c328c9\.mesonpy-w5gyi215\meson-logs\meson-log.txt
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [1]:
import boto3
import pandas as pd
import sagemaker
from pyathena import connect

sagemaker.config INFO - Not applying SDK defaults from location: C:\ProgramData\sagemaker\sagemaker\config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: C:\Users\dcode\AppData\Local\sagemaker\sagemaker\config.yaml

In [2]:
session = boto3.session.Session()
region = session.region_name
sagemaker_session = sagemaker.Session()
bucket = sagemaker_session.default_bucket()

sagemaker_client = boto3.Session().client(service_name="sagemaker", region_name=region)
s3_client = boto3.Session().client(service_name="s3", region_name=region)

Couldn't call 'get_role' to get Role ARN from role name voclabs to get Role path.

In [3]:
S3_DATA_PATH = f"s3://{bucket}/final_project/data"
!aws s3 cp "../data/DDoS-Friday-no-metadata.parquet" $S3_DATA_PATH/

Completed 1.0 MiB/27.5 MiB (1.9 MiB/s) with 1 file(s) remaining
Completed 2.0 MiB/27.5 MiB (2.4 MiB/s) with 1 file(s) remaining
Completed 3.0 MiB/27.5 MiB (3.2 MiB/s) with 1 file(s) remaining
Completed 4.0 MiB/27.5 MiB (4.0 MiB/s) with 1 file(s) remaining
Completed 5.0 MiB/27.5 MiB (4.4 MiB/s) with 1 file(s) remaining
Completed 6.0 MiB/27.5 MiB (5.1 MiB/s) with 1 file(s) remaining
Completed 7.0 MiB/27.5 MiB (5.9 MiB/s) with 1 file(s) remaining
Completed 8.0 MiB/27.5 MiB (6.3 MiB/s) with 1 file(s) remaining
Completed 9.0 MiB/27.5 MiB (4.9 MiB/s) with 1 file(s) remaining
Completed 10.0 MiB/27.5 MiB (5.0 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/27.5 MiB (5.2 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/27.5 MiB (5.6 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/27.5 MiB (4.9 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/27.5 MiB (4.9 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/27.5 MiB (5.1 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/27.5 MiB (5.4 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/27.5 MiB (4.7 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/27.5 MiB (4.8 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/27.5 MiB (4.7 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/27.5 MiB (4.9 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/27.5 MiB (4.5 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/27.5 MiB (4.3 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/27.5 MiB (4.2 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/27.5 MiB (4.1 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/27.5 MiB (4.0 MiB/s) with 1 file(s) remaining
Completed 25.5 MiB/27.5 MiB (4.0 MiB/s) with 1 file(s) remaining
Completed 26.5 MiB/27.5 MiB (4.0 MiB/s) with 1 file(s) remaining
Completed 27.5 MiB/27.5 MiB (3.9 MiB/s) with 1 file(s) remaining
upload: ..\data\DDoS-Friday-no-metadata.parquet to s3://sagemaker-us-east-1-637423636147/final_project/data/DDoS-Friday-no-metadata.parquet

In [4]:
ATHENA_DB_NAME = "final_project"
S3_STAGING_DIR = f"s3://{bucket}/final_project/staging"
conn = connect(region_name=region, s3_staging_dir=S3_STAGING_DIR)
statement = f"CREATE DATABASE IF NOT EXISTS {ATHENA_DB_NAME}"
pd.read_sql(statement, conn)

C:\Users\dcode\AppData\Local\Temp\ipykernel_14464\270557796.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(statement, conn)

Empty DataFrame
Columns: []
Index: []

In [17]:
DATA_TABLE_NAME = "ddos_data"
create_table_statement = f"""
    CREATE EXTERNAL TABLE IF NOT EXISTS {ATHENA_DB_NAME}.{DATA_TABLE_NAME} (
      protocol int,
      flow_duration int,
      total_fwd_packets int,
      total_backward_packets int,
      fwd_packets_length_total int,
      bwd_packets_length_total int,
      fwd_packet_length_max int,
      fwd_packet_length_min int,
      fwd_packet_length_mean double,
      fwd_packet_length_std double,
      bwd_packet_length_max int,
      bwd_packet_length_min int,
      bwd_packet_length_mean double,
      bwd_packet_length_std double,
      flow_bytes_per_s double,
      flow_packets_per_s double,
      flow_iat_mean double,
      flow_iat_std double,
      flow_iat_max int,
      flow_iat_min int,
      fwd_iat_total int,
      fwd_iat_mean double,
      fwd_iat_std double,
      fwd_iat_max int,
      fwd_iat_min int,
      bwd_iat_total int,
      bwd_iat_mean double,
      bwd_iat_std double,
      bwd_iat_max int,
      bwd_iat_min int,
      fwd_psh_flags int,
      bwd_psh_flags int,
      fwd_urg_flags int,
      bwd_urg_flags int,
      fwd_header_length int,
      bwd_header_length int,
      fwd_packets_per_s double,
      bwd_packets_per_s double,
      packet_length_min int,
      packet_length_max int,
      packet_length_mean double,
      packet_length_std double,
      packet_length_variance double,
      fin_flag_count int,
      syn_flag_count int,
      rst_flag_count int,
      psh_flag_count int,
      ack_flag_count int,
      urg_flag_count int,
      cwe_flag_count int,
      ece_flag_count int,
      down_up_ratio double,
      avg_packet_size double,
      avg_fwd_segment_size double,
      avg_bwd_segment_size double,
      fwd_avg_bytes_bulk double,
      fwd_avg_packets_bulk double,
      fwd_avg_bulk_rate int,
      bwd_avg_bytes_bulk double,
      bwd_avg_packets_bulk double,
      bwd_avg_bulk_rate int,
      subflow_fwd_packets int,
      subflow_fwd_bytes int,
      subflow_bwd_packets int,
      subflow_bwd_bytes int,
      init_fwd_win_bytes int,
      init_bwd_win_bytes int,
      fwd_act_data_packets int,
      fwd_seg_size_min int,
      active_mean double,
      active_std double,
      active_max int,
      active_min int,
      idle_mean double,
      idle_std double,
      idle_max int,
      idle_min int,
      label string
    )
    STORED AS PARQUET
    LOCATION '{S3_DATA_PATH}'
    TBLPROPERTIES (
      'classification'='parquet',
      'compressionType'='snappy'
    );
"""

pd.read_sql(create_table_statement, conn)

C:\Users\dcode\AppData\Local\Temp\ipykernel_14464\1610673404.py:91: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(create_table_statement, conn)

Empty DataFrame
Columns: []
Index: []

In [18]:
statement = f"SHOW TABLES in {ATHENA_DB_NAME}"
df_show = pd.read_sql(statement, conn)
df_show

C:\Users\dcode\AppData\Local\Temp\ipykernel_14464\3285076264.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_show = pd.read_sql(statement, conn)

    tab_name
0  ddos_data

In [19]:
statement = f"""SELECT *
FROM {ATHENA_DB_NAME}.{DATA_TABLE_NAME}"""

df_show = pd.read_sql(statement, conn)
df_show.head(5)

C:\Users\dcode\AppData\Local\Temp\ipykernel_14464\2904911201.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_show = pd.read_sql(statement, conn)

,protocol,flow_duration,total_fwd_packets,total_backward_packets,fwd_packets_length_total,bwd_packets_length_total,fwd_packet_length_max,fwd_packet_length_min,fwd_packet_length_mean,fwd_packet_length_std,...,fwd_seg_size_min,active_mean,active_std,active_max,active_min,idle_mean,idle_std,idle_max,idle_min,label
0,6,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
1,6,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
2,6,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
3,6,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign
4,6,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Benign